package examer.db;


import examer.Settings;
import java.util.ArrayList;
import java.util.HashMap;
import org.sicut.sqlite.Table;

/**
 *
 * Generated by: S2JConverter
 * at 2020-12-24, 16:22:08
 * @author Hafid KASSIMI
 */

public final class Exam extends Table {
    
    
    private int idExam;
    private String label;
    private String examSession;
    private String examLevel;
    private final int dummyIdCenter = 0;
    private int idCenter = dummyIdCenter;

    public Exam() {
        super();
        setDatabase(Settings.DB_PATH);
        name = "Exam";
    }
    
    public Exam(int idExam, String label, String examSession, String examLevel) {
        this();
        
        this.idExam = idExam;
        this.label = label;
        this.examSession = examSession;
        this.examLevel = examLevel;
    }
    
    public Exam(int idExam) {
        this();
        HashMap<String, ArrayList> res = super.select("1 and idExam='" + idExam + "'");
        
        this.idExam = idExam;
        if ( res.get(res.keySet().iterator().next()).size() > 0 ) {
            
            label = res.get("label").get(0).toString();
            examSession = res.get("examSession").get(0).toString();
            examLevel = res.get("examLevel").get(0).toString();
        }
        else {
            
            label = "";
            examSession = "";
            examLevel = "";
        }
    }
    
    public ArrayList<Exam> list() {
        HashMap<String, ArrayList> res = super.select("idExam<>" + dummyIdCenter);
        ArrayList<Exam> l = new ArrayList();
        for ( int i = 0, n = res.get(res.keySet().iterator().next()).size(); i < n; i++ ) {
            l.add( new Exam( (int) res.get("idExam").get(i), res.get("label").get(i).toString(), res.get("examSession").get(i).toString(), res.get("examLevel").get(i).toString() ) );
        }
        return l;
    }
    
    public boolean delete() {
        return delete2("1 and idExam='" + idExam + "'");
    }
    
    public boolean update() {
        
        fv_pairs.put("idExam", idExam);
        fv_pairs.put("label", label);
        fv_pairs.put("examSession", examSession);
        fv_pairs.put("examLevel", examLevel);
        fv_pairs.put("idCenter", idCenter);
        return update2("1 and idExam='" + idExam + "'");
    }
    
    public boolean moveAllToDummyCenter() {
        
        fv_pairs.clear();
        fv_pairs.put("idCenter", dummyIdCenter);
        return update2("1");
    }

    public boolean moveTo(int idCenter) {
        fv_pairs.clear();
        fv_pairs.put("idCenter", idCenter);
        return update2("idExam=" + idExam);
    }
    
    public boolean save() {
        
        fv_pairs.put("idExam", idExam);
        fv_pairs.put("label", label);
        fv_pairs.put("examSession", examSession);
        fv_pairs.put("examLevel", examLevel);
        fv_pairs.put("idCenter", idCenter);
        return insert();
    }
    
    
    public int count() {
        HashMap<String, ArrayList> res = super.select(new String[] {"count(*) as n"}, 
                "idExam<>" + dummyIdCenter + " and idExam=" + idExam + " and label like '"
                + label + "' and examSession like '" + examSession + "'");
        try {
            return (int) res.get("n").get(0);
        }
        catch ( Exception e ) {
            return 0;
        }
    }
    
    
    public int nextIdexam() {
        HashMap<String, ArrayList> res = super.select(new String[] {"max(idExam) as idExam"}, "1");
        try {
            return (int) res.get("idExam").get(0) + 1;
        }
        catch ( Exception e ) {
            return 1;
        }
    }
    
    
    public void setIdexam(int idExam) {
        this.idExam = idExam;
    }

    public int getIdexam() {
        return idExam;
    }
    public void setLabel(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

    public String getExamSession() {
        return examSession;
    }

    public void setExamSession(String examSession) {
        this.examSession = examSession;
    }
    
    @Override
    public String toString(){
        return label + " (" + examSession + ")";
    }

    public int getIdCenter() {
        return idCenter;
    }

    public void setIdCenter(int idCenter) {
        this.idCenter = idCenter;
    }

    public String getExamLevel() {
        return examLevel;
    }

    public void setExamLevel(String examLevel) {
        this.examLevel = examLevel;
    }

    public void clone(Exam exam) {
        idExam = exam.getIdexam();
        label = exam.getLabel();
        examSession = exam.getExamSession();
        examLevel = exam.getExamLevel();
    }
}