package examer.db;


import examer.Settings;
import java.util.ArrayList;
import java.util.HashMap;
import org.sicut.sqlite.Table;

/**
 *
 * Generated by: S2JConverter
 * at 2020-12-24, 16:22:08
 * @author Hafid KASSIMI
 */

public final class Sfl extends Table {
    
    
    private int idSFL;
    private String abrev;
    private String label;

    public Sfl() {
        super();
        setDatabase(Settings.DB_PATH);
        name = "SFL";
    }
    
    public Sfl(int idSFL, String abrev, String label) {
        this();
        
        this.idSFL = idSFL;
        this.abrev = abrev;
        this.label = label;
    }
    
    public Sfl(int idSFL) {
        this();
        HashMap<String, ArrayList> res = super.select("1 and idSFL='" + idSFL + "'");
        
        this.idSFL = idSFL;
        if ( res.get(res.keySet().iterator().next()).size() > 0 ) {
            
            abrev = res.get("abrev").get(0).toString();
            label = res.get("label").get(0).toString();
        }
        else {
            
            abrev = "";
            label = "";
        }
    }
    
    public ArrayList<Sfl> list() {
        HashMap<String, ArrayList> res = super.select();
        ArrayList<Sfl> l = new ArrayList();
        for ( int i = 0, n = res.get(res.keySet().iterator().next()).size(); i < n; i++ ) {
            l.add( new Sfl( (int) res.get("idSFL").get(i), res.get("abrev").get(i).toString(), res.get("label").get(i).toString() ) );
        }
        return l;
    }
    
    public boolean delete() {
        return delete2("1 and idSFL='" + idSFL + "'");
    }
    
    public boolean update() {
        
        fv_pairs.put("idSFL", idSFL);
        fv_pairs.put("abrev", abrev);
        fv_pairs.put("label", label);
        return update2("1 and idSFL='" + idSFL + "'");
    }
    
    public boolean save() {
        
        fv_pairs.put("idSFL", idSFL);
        fv_pairs.put("abrev", abrev);
        fv_pairs.put("label", label);
        return insert();
    }
    
    
    public int nextIdsfl() {
        HashMap<String, ArrayList> res = super.select(new String[] {"max(idSFL) as idSFL"}, "1");
        try {
            return (int) res.get("idSFL").get(0) + 1;
        }
        catch ( Exception e ) {
            return 1;
        }
    }
    
    
    public void setIdsfl(int idSFL) {
        this.idSFL = idSFL;
    }

    public int getIdsfl() {
        return idSFL;
    }
    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }

    public String getAbrev() {
        return abrev;
    }
    public void setLibelle(String label) {
        this.label = label;
    }

    public String getLibelle() {
        return label;
    }

}